"""Synthetic UEG analytic-continuation test problem.

Loads the base spectral function (completed Mermin DSF) and prior (RPA model)
from pre-computed physics data, then generates test problems at a specified
normalization scale Z. The self-scaling Newton method should discover τ* ≈ Z.

Base data (`data/synthetic-UEG_testproblem.npz`) was generated by T. Chuna
using the completed Mermin and RPA models of the dynamic structure factor;
see Chuna et al. (2025) for the physics.

Command-line usage
------------------
    python -m selfscaling.ueg                        # Z=1 (simplex-normalized)
    python -m selfscaling.ueg --Z 5.0                # Z=5
    python -m selfscaling.ueg --Z 3 --noise 1e-3 --seed 123

Output is saved to `data/ueg_problem.npz` relative to the repo root.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


# Repo layout: <repo>/src/selfscaling/ueg.py  →  parents[2] == <repo>
_REPO_ROOT = Path(__file__).resolve().parents[2]
BASE_DATA = _REPO_ROOT / "data" / "synthetic-UEG_testproblem.npz"


def build_kernel(taus, omegas, beta):
    """Two-sided periodic Laplace kernel.

    A_{ij} = exp(-τ_i ω_j) + exp(-(β - τ_i) ω_j)

    This is the finite-temperature kernel for analytic continuation of
    imaginary-time correlation functions; see Chuna et al. (2025), eq. (4).
    """
    T = np.outer(taus, omegas)
    return np.exp(-T) + np.exp(-(beta - taus[:, None]) * omegas[None, :])


def generate_ueg_problem(Z: float = 1.0,
                         noise_level: float = 1e-4,
                         n_samples: int = 1000,
                         seed: int = 42) -> dict:
    """Generate a UEG analytic-continuation test problem.

    Parameters
    ----------
    Z : float
        Normalization scale. The ground-truth spectral function is
        x_true = Z * x_base, where x_base ∈ Δ_n (simplex). The
        self-scaling algorithm should recover τ* ≈ Z.
    noise_level : float
        Relative noise amplitude (multiplicative, growing with τ).
    n_samples : int
        Number of noisy samples used to form b (mean) and b_std.
    seed : int
        RNG seed for reproducibility.

    Returns
    -------
    dict
        Keys: A, b, b_std, mu, x_true, Z, taus, omegas, beta.
    """
    base = np.load(BASE_DATA)
    x_base = base["x"].astype(np.float64)   # completed Mermin DSF, sum ≈ 1
    mu = base["mu"].astype(np.float64)       # RPA prior, sum ≈ 1
    taus = base["taus"]
    omegas = base["omegas"]
    beta = taus[-1]

    A = build_kernel(taus, omegas, beta)

    x_true = Z * x_base
    b_exact = A @ x_true

    # Multiplicative noise model (Chuna et al.):
    #   b_sample = (1 + noise_level * η * τ/Δτ) * b_exact,  η ~ N(0, I).
    rng = np.random.default_rng(seed)
    dtau = taus[1] - taus[0]
    tau_factor = taus / dtau
    samples = np.empty((n_samples, len(taus)))
    for k in range(n_samples):
        eta = rng.standard_normal(len(taus))
        samples[k] = (1.0 + noise_level * eta * tau_factor) * b_exact

    b = samples.mean(axis=0)
    b_std = samples.std(axis=0)

    return dict(A=A, b=b, b_std=b_std, mu=mu, x_true=x_true,
                Z=np.float64(Z), taus=taus, omegas=omegas, beta=np.float64(beta))


def main():
    parser = argparse.ArgumentParser(description="Generate a UEG test problem.")
    parser.add_argument("--Z", type=float, default=1.0,
                        help="Normalization scale (default: 1.0)")
    parser.add_argument("--noise", type=float, default=1e-4,
                        help="Relative noise level (default: 1e-4)")
    parser.add_argument("--samples", type=int, default=1000,
                        help="Number of noisy samples (default: 1000)")
    parser.add_argument("--seed", type=int, default=42,
                        help="RNG seed (default: 42)")
    parser.add_argument("--output", type=Path, default=None,
                        help="Output path (default: data/ueg_problem.npz)")
    args = parser.parse_args()

    data = generate_ueg_problem(Z=args.Z, noise_level=args.noise,
                                n_samples=args.samples, seed=args.seed)

    out_path = args.output or (_REPO_ROOT / "data" / "ueg_problem.npz")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez(out_path, **data)

    x = data["x_true"]
    b = data["b"]
    A = data["A"]
    resid = np.linalg.norm(A @ x - b) / np.linalg.norm(b)
    print(f"Saved {out_path}")
    print(f"  Z = {args.Z},  sum(x_true) = {x.sum():.6f}")
    print(f"  m = {A.shape[0]},  n = {A.shape[1]},  beta = {data['beta']:.4f}")
    print(f"  ||Ax - b|| / ||b|| = {resid:.4e}")


if __name__ == "__main__":
    main()
